version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: kiita-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=kiita
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
