### Find comments
GET http://localhost:8080/api/comments/1
Accept: application/json

### Find an post
GET http://localhost:8080/api/posts/1
Accept: application/json

<> 2023-05-30T103522.200.json

### Create an post
POST http://localhost:8080/api/posts
Content-Type: application/json

{
  "title": "テストタイトル",
  "body": "ボディ"
}

<> 2023-05-31T104058.201.json

### Update an post
PATCH http://localhost:8080/api/posts/7
Content-Type: application/json

{
  "title": "タイトル",
  "body": "ボディ"
}

### Delete a post
DELETE http://localhost:8080/api/posts/1
Content-Type: application/json
