### Find post summaries
GET http://localhost:8080/api/posts
Accept: application/json

### Find an user
GET http://localhost:8080/api/users/1
Accept: application/json

### Create an user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "lastName": "山田",
  "firstName": "三郎"
}

### Update an user
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "lastName": "山田",
  "firstName": "三郎"
}

### Delete an user
DELETE http://localhost:8080/api/users/1
Content-Type: application/json
